### ISSUE TITLE
Null check operator used on a null value 

### ISSUE THREAD

**Issue by heshesh2010** [marcglasberg/image_pixels#13]
he following _TypeError was thrown building ImagePixels(dirty, state: _ImagePixelsState#d22d7):
Null check operator used on a null value

The relevant error-causing widget was
ImagePixels
sard_widget.dart:290
When the exception was thrown, this was the stack
#0      _FeedSardWidgetState.build.<anonymous closure>

```

`ImagePixels(
                        imageProvider: CachedNetworkImageProvider(
                          "https://storage.googleapis.com/siyaq-videos/b7g3uge8kla3v4xsrnuh8fbz5g6db6s3.jpg",
                          //   maxHeight: 600,
                          maxWidth: Get.width.toInt(),
                        ),
                        defaultColor: Colors.grey,
                        builder: (context, img) => img.height! > 600
                            ? CachedNetworkImage(
                                imageUrl:
                                    "https://storage.googleapis.com/siyaq-videos/b7g3uge8kla3v4xsrnuh8fbz5g6db6s3.jpg",
                                fit: BoxFit.fitWidth,
                                width: double.infinity,
                                filterQuality: FilterQuality.high,
                                height: 600.h,
                              )
                            : CachedNetworkImage(
                                width: double.infinity,
                                imageUrl:
                                    "https://storage.googleapis.com/siyaq-videos/b7g3uge8kla3v4xsrnuh8fbz5g6db6s3.jpg",
                                fit: BoxFit.fitWidth,
                                // // (widget.sard.content![0].file!.heightInPx! /
                                // Get.pixelRatio)
                              ),
                      )`
```

**Comment by heshesh2010** [comment]
I added loading widget when hasImage is false , so when image downloaded it shows without any error

**Comment by marcglasberg** [comment]
Ok, good that you found the problem on your end, but in any case I'm not sure what your are trying to do actually makes sense.

It seems to me you are trying to check the size of an image, and if the image is large (> 600px) you want to download it with high quality. If the image is small you want to download it with less quality. This doesn't work, because `ImagePixels` actually already needs to download the image to check its size. At this point you already downloaded the image, so it doesn't make sense to try and download it again with less quality.
